name: Lint
run-name: Deploy initiated by ${{ github.actor }}

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint codebase
        uses: github/super-linter/slim@v4
        env:
          # Don't know why you need this, but you do
          # Ref: https://github.com/github/super-linter/issues/533
          # It just needs to be passed to elevate permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
        
