name: Lint
run-name: Deploy initiated by ${{ github.actor }}

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Python3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint
        uses: wearerequired/lint-action@v2.3.0
        with:
          flake8: true
