name: Lint@v2
run-name: Linting initiated by ${{ github.actor }}

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black flake8
      
      # - name: Pylint
      #   run: |
      #     pylint $(git ls-files "*.py")

      - name: Flake8
        run: |
          flake8 $(git ls-files "*.py")


      


